### ISSUE TITLE
Spotify Plugin fails to download

### ISSUE THREAD

**Issue by n8klayko** [IcySnex/Melora#2]
I have been able to use Melora to download from YouTube successfully,, but the Spotify plugin appears to not work correctly. I have not been able to get past the 403 (Forbidden) message as seen in the attached images. Am I missing something or this issue happening on your end too? I have FFMPEG installed and have configured Melora according to the guide and my preferences and have installed to latest versions of the plugins. Also, running on Win10 x64.

![issue](https://github.com/user-attachments/assets/f7d61648-6df0-44a9-a053-dba56cdd49af)

![issue2](https://github.com/user-attachments/assets/500db631-8ddf-42b9-aa96-04f3d816ad8c)

**Comment by n8klayko** [comment]
Also, I tried adding my developer client ID and secret, but I get this this error before and after adding mine. I have tested it with a previously working app, but that app stopped working a few months ago or so.

**Comment by IcySnex** [comment]
Hello,
First of all, thank you for your interest in Melora and for taking the time to report this issue.

I have checked and was able to successfully reproduce the problem you have described. 
It looks like there is an issue with the underlaying service that handles download Spotify tracks.

I will debug this and release a fix as soon as possible. I will notify you in this GitHub Issue for when that happens.

**Comment by n8klayko** [comment]
Thanks, I really do love the interface and simplicity. Glad to report I found. If you ever need help testing or anything like that, I'd be happy to help how I can as well!

**Comment by IcySnex** [comment]
Hello, I have finally fixed the Spotify plugin. The plugin is now using YouTube Music as the download source. While this is not the best solution, its the best and most reliable for now.

The plugin might struggle with unknown artists or Spotify-Only songs. To further improve accuracy you can change the "YouTube Music Search Format" in the settings to optimize how the plugin searches on YouTube Music.

To update the plugin, just download the latest version from the [Plugin Collection](https://icysnex.github.io/Melora/plugin-collection/platform-support.html), remove the old plugin from the Melora Plugin Bundles page and import the new one.

If any other questions occur, don't hesitate to open a new issue. Thank you for your patience!
